OnlineJewelleryStore/Controllers/ProductDashboardController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineJewelleryStore.Models;
using OnlineJewelleryStore.Repository;

namespace OnlineJewelleryStore.Controllers
{
    public class ProductDashboardController : Controller
    {
        MainRepository mainRepo = new MainRepository();
        public ActionResult ProductIndex(int selectedId)
        {
            ViewBag.SelectedId = selectedId;
            return View(mainRepo);
        }
        public ActionResult Create(int selectedId)
        {
            ViewBag.SelectedId = selectedId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tbl_Product product)
        {

            TryUpdateModel(product);
            if (ModelState.IsValid)
            {
                string categoryName = mainRepo.GetCategoryName(product.CategoryId);
                string imagePath = "~/Content/Images/" + categoryName + "/" + product.ImageFile.FileName;
                product.Image = imagePath;
                product.ImageFile.SaveAs(Server.MapPath(imagePath));
                mainRepo.db.Tbl_Product.Add(product);
                mainRepo.db.SaveChanges();
                return RedirectToAction("ProductIndex", new { selectedId = product.CategoryId });
            }

            return View(product);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Product productItem  = mainRepo.db.Tbl_Product.Find(id);
            if (productItem == null)
            {
                return HttpNotFound();
            }
            return View(productItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Tbl_Product product)
        {
            // We dont want count/ empty image from the edited product, so using the id of the
            // edited product, we are retrieving the record from database and applying
            // all the changes except count/ empty image.
            Tbl_Product productInDb = mainRepo.db.Tbl_Product.Single(x => x.Id == product.Id);
            // if the user gives a new image file, update the product
            // in database with the given image.
            try
            {
                productInDb.ImageFile = product.ImageFile;
                string categoryName = mainRepo.GetCategoryName(product.CategoryId);
                string imagePath = "~/Content/Images/" + categoryName + "/" + product.ImageFile.FileName;
                productInDb.Image = imagePath;
                productInDb.ImageFile.SaveAs(Server.MapPath(imagePath));
            }
            catch (NullReferenceException)
            {
                // No new image file choosen by the user.
            }
            productInDb.Name = product.Name;
            productInDb.IsActive = product.IsActive;
            productInDb.CreatedDate = product.CreatedDate;
            productInDb.Description = product.Description;
            productInDb.IsFeatured = product.IsFeatured;
            productInDb.Quantity = product.Quantity;
            productInDb.Price = product.Price;
            TryUpdateModel(productInDb);
            if (ModelState.IsValid)
            {
                mainRepo.db.Entry(productInDb).State = EntityState.Modified;
                mainRepo.db.SaveChanges();
                return RedirectToAction("ProductIndex", new { selectedId = product.CategoryId });
            }
            return View(productInDb);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Product product = mainRepo.db.Tbl_Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Product product = mainRepo.db.Tbl_Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Product product = mainRepo.db.Tbl_Product.Find(id);
            mainRepo.db.Tbl_Product.Remove(product);
            mainRepo.db.SaveChanges();
            return RedirectToAction("ProductIndex", new { selectedId = product.CategoryId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                mainRepo.db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineJewelleryStore/Views/ProductDashboard/Create.cshtml
@model OnlineJewelleryStore.Models.Tbl_Product

@{
    ViewBag.Title = "CreateProduct";
}

@using (Html.BeginForm("Create", "ProductDashboard", FormMethod.Post, new { enctype = "multipart/form-data", id = "createForm" }))
{
    @Html.AntiForgeryToken()
<div class="form-control-static" id="container" style="padding:30px;">
    <div id="main">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header bg-primary text-center text-capitalize">
                    <h2 class=" category-heading">Create Product</h2>
                </div>
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="logo-div">
            <div class="form-group">
                <div class="col-md-12 image-upload ">
                    <input type="file" name="ImageFile" class="btn btn-primary btn-sm float-left">
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2 textBox" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-12">
                @Html.DropDownList(
                    "CategoryId",
                    new List<SelectListItem> {
                        new SelectListItem{Text = "Bracelets", Value = "1", Selected = true},
                        new SelectListItem{Text = "Ear Rings", Value = "2"},
                        new SelectListItem{Text = "Necklace Sets", Value = "3"},
                        new SelectListItem{Text = "Rings", Value = "4"},
                    },
                    htmlAttributes: new { @class = "form-control" }
                )
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsFeatured, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.IsFeatured, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsFeatured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12" style="padding-top:10px">
                <input type="submit" value="Create" class="btn btn-primary btn-sm createButton" />
                @Html.ActionLink(
                    "Back",
                    "ProductIndex",
                    "ProductDashboard",
                    new { selectedId = ViewBag.SelectedId },
                    new {
                        @class = "btn btn-primary btn-sm backButton",
                    }
                )
            </div>
        </div>
    </div>
</div>

    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    @section scripts
{
        <script>
        $(function () {
            $(".datepicker").datepicker(
                {
                    dateFormat : "yy-mm-dd"
                });
        });
        </script>
    }
}

OnlineJewelleryStore/Views/ProductDashboard/Delete.cshtml
@model OnlineJewelleryStore.Models.Tbl_Product

@{
    ViewBag.Title = "Delete";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-control-static" style="padding:30px;">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header bg-danger text-center">
                <h2 class=" category-heading">Delete @Model.Name ?</h2>
            </div>
        </div>
    </div>
    <dl class="dl-horizontal">
        <div class="logo-div">
            <dd>
                <img src="@Url.Content(Model.Image)" width="200" height="200" />
            </dd>
        </div>
        <dl class="details-div">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsFeatured)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsFeatured)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tbl_Category.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tbl_Category.Name)
            </dd>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="margin-top:10px">
                    <input type="submit" value="Delete" class="btn btn-primary btn-sm deleteButton" />
                    @Html.ActionLink(
                             "Back",
                             "ProductIndex",
                             "ProductDashboard",
                             new { selectedId = Model.CategoryId },
                             new
                             {
                                 @class = "btn btn-primary btn-sm backButton",
                             }
                         )
                </div>
            </div>

        </dl>
    </dl>

</div>
}

OnlineJewelleryStore/Views/ProductDashboard/Details.cshtml
@model OnlineJewelleryStore.Models.Tbl_Product

@{
    ViewBag.Title = "Details";
}

<div class="form-control-static" id="container" style="padding:30px;">
    <div id="main">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header bg-primary text-center">
                    <h2 class=" category-heading">@Model.Name Details</h2>
                </div>
            </div>
        </div>
        <dl class="dl-horizontal">
            <div class="logo-div">
                <dd>
                    <img src="@Url.Content(Model.Image)" width="200" height="200" />
                </dd>
            </div>
            <div class="details-div">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsFeatured)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsFeatured)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Quantity)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Quantity)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Price)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Tbl_Category.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tbl_Category.Name)
                </dd>
            </div>
        </dl>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary btn-sm editButton" })
            @Html.ActionLink("Back", "ProductIndex", "ProductDashboard", new { selectedId = Model.CategoryId }, new { @class = "btn btn-primary btn-sm backButton", @style = "float:left" })
        </p>
    </div>

</div>

OnlineJewelleryStore/Views/ProductDashboard/Edit.cshtml
@model OnlineJewelleryStore.Models.Tbl_Product

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "ProductDashboard", FormMethod.Post, new { enctype = "multipart/form-data", id = "editForm" }))
{
    @Html.AntiForgeryToken()
<div class="form-control-static" id="container" style="padding:30px;">
    <div id="main">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="row">
            <div class="col-md-12">
                <div class="page-header bg-primary text-center text-capitalize">
                    <h2 class=" category-heading">Update Product - @Model.Name</h2>
                </div>
            </div>
        </div>
        <div class="logo-div">
            <div class="form-group">
                <div class="col-md-12 image-upload ">
                    <img src="@Url.Content(Model.Image)" width="200" height="200" />
                    <input type="file" name="ImageFile" class="btn btn-primary btn-sm float-left">
                </div>
            </div>
        </div>

        <div class="edit-div">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-12">
                    @Html.DropDownList(
                        "CategoryId",
                        new List<SelectListItem> {
                            new SelectListItem{Text = "Bracelets", Value = "1", Selected = true},
                            new SelectListItem{Text = "Ear Rings", Value = "2"},
                            new SelectListItem{Text = "Necklace Sets", Value = "3"},
                            new SelectListItem{Text = "Rings", Value = "4"},
                        },
                        htmlAttributes: new { @class = "form-control" }
                    )
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-3 " })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsFeatured, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.IsFeatured, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsFeatured, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="padding-top:10px">
                    <input type="submit" value="Save" class="btn btn-primary btn-sm saveButton" />
                    @Html.ActionLink(
                        "Back",
                        "ProductIndex",
                        "ProductDashboard",
                        new { selectedId = Model.CategoryId },
                        new {
                            @class = "btn btn-primary btn-sm backButton",
                        }
                    )
                </div>
            </div>
        </div>
    </div>
</div>
}
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
@section scripts
{
    <script>
        $(function () {
            $(".datepicker").datepicker(
                {
                        dateFormat: "yy-mm-dd"
                    });
        });
    </script>
}

OnlineJewelleryStore/Views/ProductDashboard/ProductIndex.cshtml
@model OnlineJewelleryStore.Repository.MainRepository

@{
    ViewBag.Title = "ProductIndex";
}
<div class="container" id="container" style="padding-top:30px;">
    <div id="main">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header bg-primary text-center text-capitalize">
                    <h2 class=" category-heading">Product Admin Dashboard</h2>
                </div>
            </div>
        </div>
        @{List<SelectListItem> dropDownItems = new List<SelectListItem>(); }
        @foreach (var category in Model.GetAllCategories())
        {
            dropDownItems.Add(
                new SelectListItem
                {
                    Text = category.Name,
                    Value = Url.Action(
                        "ProductIndex",
                        "ProductDashboard",
                        new { selectedId = category.Id }
                    ),
                    Selected = category.Id == ViewBag.SelectedId
                }
            );
        }
        <h4 style="display:inline-block;position:relative;top:2px;" class="text-primary">Category: </h4>
        @Html.DropDownList(
            "CategoryId",
            dropDownItems,
            htmlAttributes: new {
                @class = "btn btn-primary btn-sm ca",
                @id = "categoryddl"
            }
        )
        @{
            string categoryName = Model.GetCategory(ViewBag.SelectedId).Name;
            categoryName = categoryName.Remove(categoryName.Length - 1);
        }
        @Html.ActionLink(
            "Create New " + categoryName,
            "Create",
            new { selectedId = ViewBag.SelectedId},
            new {
                @class = "btn btn-primary btn-sm createButton",
            }
        )
        <br />
        <br />
        <div class="row product-container">
            @foreach (var product in Model.GetProductsByCategoryId(ViewBag.SelectedId))
            {
                <div class="col-md-3 col-sm-6 col-xs-10" style="margin-bottom:8px">
                    <div class="thumbnail product-item">
                        <img class="media-resize" title="click to view product detail"
                             src=@Url.Content(product.Image) />
                        <div class="caption">
                            <h5 class="text-primary">@product.Name</h5>
                            <p class="text-danger" style="font-weight:bold">£@product.Price</p>
                            <div class="product-item-badge">New</div>
                        </div>
                        @Html.ActionLink(
                            "Edit",
                            "Edit",
                            new { id = product.Id },
                            new { @class = "btn btn-primary btn-sm editButton" }
                        )
                        @Html.ActionLink(
                            "Details",
                            "Details",
                            new { id = product.Id },
                            new { @class = "btn btn-primary btn-sm detailsButton" }
                        )
                        @Html.ActionLink(
                            "Delete",
                            "Delete",
                            new { id = product.Id },
                            new { @class = "btn btn-primary btn-sm deleteButton" }
                        )
                    </div>
                </div>
            }
        </div>
        @Html.ActionLink(
            "Back to Home Page ",
            "Index",
            "Home",
            new {},
            new {
                @class = "btn btn-primary btn-sm backButton",
                @style = "float:right;"
            }
        )
        <br />
        <br />
    </div>
</div>

<script>
    $(function () {
        $('#categoryddl').change(function () {
            var url = $(this).val();
            if (url != null && url != '') {
                window.location.href = url;
            }
        });
    });
</script>